<a href="https://colab.research.google.com/github/revathiuddagiri9-creator/Nasscom-lab/blob/main/Nasscom_numpy_operator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numppy

ERROR: Could not find a version that satisfies the requirement numppy (from versions: none)
ERROR: No matching distribution found for numppy


In [2]:
pip install numpy

In [8]:
import numpy as np#1d array#
a=np.array((1,2,3))
print(a)
print(a.dtype)
print(a.shape)

[1 2 3]
int64
(3,)


In [7]:
#2d array#
b=np.array([[1,2,3],[4,5,6],[6,8,9]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]
 [6 8 9]]
(3, 3)


In [9]:
#3d array#
b=np.array([[[1,2]]])
print(b.shape)

(1, 1, 2)


In [18]:
#number of dimensions#
a=np.array(43)
b=np.array([1,2,3])
c=np.array([[1,2],[3,4]])
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
#copy#
arr = np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)


0
1
2
3
[42  2  3  4  5]
[1 2 3 4 5]


In [14]:
#view#
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [19]:
#reshaping arrays#
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
#linear algebra#
A=np.array([[1,2],[3,4]])
B=np.array([5,6])
x=np.linalg.solve(A,B)
print(x)

[-4.   4.5]


In [24]:
#Access the elements#
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('5th element on 2nd dim: ',arr[1,4])

5th element on 2nd dim:  10


In [25]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [26]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Last element from 2nd dim: ',arr[-2,-1])

Last element from 2nd dim:  5
