<a href="https://colab.research.google.com/github/revathiuddagiri9-creator/Nasscom-lab/blob/main/Nasscom_numpy_operator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numppy

ERROR: Could not find a version that satisfies the requirement numppy (from versions: none)
ERROR: No matching distribution found for numppy


In [2]:
pip install numpy

In [8]:
import numpy as np#1d array#
a=np.array((1,2,3))
print(a)
print(a.dtype)
print(a.shape)

[1 2 3]
int64
(3,)


In [7]:
#2d array#
b=np.array([[1,2,3],[4,5,6],[6,8,9]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]
 [6 8 9]]
(3, 3)


In [9]:
#3d array#
b=np.array([[[1,2]]])
print(b.shape)

(1, 1, 2)


In [10]:
a=np.array(43)
print(a.ndim)
arr = np.array([1,2,3,4,5])
x=arr.copy()#copy,view,reshape#


0


In [12]:
#linear algebra#
A=np.array([[1,2],[3,4]])
B=np.array([5,6])
x=np.linalg.solve(A,B)
print(x)

[-4.   4.5]
