<a href="https://colab.research.google.com/github/revathiuddagiri9-creator/Nasscom-lab/blob/main/NumPy_Practice_Exercises_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Practice Exercises

Solve each question in the code cell below it. Do not just re-run the lab examples — use **different numbers/data** than what was shown in class so you are actually writing the logic yourself.

Run each cell with **Shift + Enter** and check that your output makes sense before moving to the next question.

### Q1. Creating a 1-D array
Create a 1-D NumPy array containing 6 numbers of your choice. Print the array and print its type using `type()`.

In [1]:
# Write your code here
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
print(arr)
print(type(arr))

[10 20 30 40 50 60]
<class 'numpy.ndarray'>


### Q2. Creating a 2-D array
Create a 2-D NumPy array with 3 rows and 2 columns (any numbers). Print the array.

In [3]:
# Write your code here

arr= np.array([[10, 20], [30, 40], [50, 60]])

print(arr)




[[10 20]
 [30 40]
 [50 60]]


### Q3. Creating a 3-D array
Create a 3-D NumPy array made up of two 2x3 matrices (2 blocks, each with 2 rows and 3 columns). Print the array.

In [6]:
# Write your code here

import numpy as np

arr= np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

print(arr)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Q4. Checking the number of dimensions
Using the three arrays you created in Q1, Q2, and Q3, print the number of dimensions of each using the `.ndim` attribute.

In [8]:
# Write your code here
import numpy as np

a1 = np.array([[1,2],[3,4],[5,6]])
a2 = np.array([[1,2],[3,4],[5,6]])
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(a1.ndim, a2.ndim, a3.ndim)


2 2 3


### Q5. Accessing elements with indexing
Create a 2-D array with 2 rows and 5 columns of your own numbers.
1. Print the 3rd element of the 1st row using positive indexing.
2. Print the last element of the 2nd row using **negative** indexing.

In [11]:
# Write your code here
arr = np.array([[10, 20, 30, 40, 50],[60, 70, 80, 90, 100]])

print(arr[0, 2])
print(arr[1, -1])


30
100


### Q6. Accessing elements in a 3-D array
Using the 3-D array you created in Q3, access and print one specific element using three indices, e.g. `arr[block, row, col]`.

In [12]:
# Write your code here
import numpy as np

arr = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

print(arr[0, 1, 2])


6


### Q7. Checking data type
Create one NumPy array of integers and one NumPy array that contains at least one decimal number. Print the `.dtype` of each and explain in a comment why they are different.

In [15]:
# Write your code here
a= np.array([1, 2, 3, 4])
b = np.array([1, 2.5, 3, 4])

print( a.dtype)
print(b.dtype)
#int64: Used strictly for whole numbers (like 1, 2, 3). It takes up exactly 64 bits of memory per number and cannot store fractions or decimals.
#float64: Used for decimal numbers (like 2.5). The "floating-point" format splits the 64 bits of memory to track both the base digits and where the decimal point goes.



int64
float64


### Q8. Copy vs View
Create a 1-D array. Make a **copy** of it using `.copy()` and a **view** of it using `.view()`. Change the first element of the original array, then print the original array, the copy, and the view. In a comment, explain what you observe and why.

In [16]:
# Write your code here
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

copy_arr = arr.copy()
view_arr = arr.view()

arr[0] = 100

print("Original array:", arr)
print("Copy:", copy_arr)
print("View:", view_arr)




Original array: [100   2   3   4   5]
Copy: [1 2 3 4 5]
View: [100   2   3   4   5]


### Q9. Shape of an array
1. Create a 2-D array with 3 rows and 4 columns and print its `.shape`.
2. Create a 1-D array of 4 numbers with `ndmin=5` and print both the array and its shape.

In [17]:
# Write your code here
import numpy as np

arr_2d = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

print(arr_2d.shape)

arr_1d = np.array([1, 2, 3, 4], ndmin=5)

print(arr_1d)
print(arr_1d.shape)



(3, 4)
[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


### Q10. Reshaping arrays
Create a 1-D array with 15 elements. Reshape it into a 2-D array with 3 rows and 5 columns using `.reshape()`. Print the result.

In [18]:
# Write your code here
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
reshaped_arr = arr.reshape(3, 5)
print(reshaped_arr)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


### Q11. Linear algebra with NumPy
Solve the following system of equations using `np.linalg.solve()`:

2x + y = 11

x + 3y = 18

Print the values of x and y.

In [20]:
# Write your code here
a= np.array([[2, 1],[1, 3]])
b = np.array([11, 18])
x, y = np.linalg.solve(a, b)

print(x)
print( y)



3.0
5.0


### Q12. arange, zeros, and ones
1. Use `np.zeros()` to create a 4x2 array of zeros.
2. Use `np.ones()` to create a 3x3 array of ones.
3. Use `np.arange()` to create an array of numbers from 5 to 30 with a step of 5.

Print all three.

In [21]:
# Write your code here
a= np.zeros((4, 2))
b= np.ones((3, 3))
c= np.arange(5, 31, 5)
print(a)
print(b)
print(c)



[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 5 10 15 20 25 30]


### Q13. Why NumPy is faster than plain Python
Create two Python lists of 500,000 numbers each. Time how long it takes to add them element-by-element using a Python loop (or list comprehension). Then convert both lists to NumPy arrays and time how long it takes to add them using `+`. Print both times and, in a comment, state which was faster and roughly by how much.

In [22]:
# Write your code here
import numpy as np
import time

a = list(range(500000))
b = list(range(500000))

t = time.time()
[a[i] + b[i] for i in range(500000)]
p = time.time() - t

a, b = np.array(a), np.array(b)

t = time.time()
a + b
n = time.time() - t

print("Python:", p)
print("NumPy:", n)
# NumPy was faster by roughly p/n times.


Python: 0.07422590255737305
NumPy: 0.0027594566345214844


### Q14. Vectors vs matrices
Create a 1-D NumPy array representing a single customer's features: `[height_cm, weight_kg, age]` (make up your own values). Then create a 2-D NumPy array representing 4 different customers with the same 3 features each. Print the `.shape` and `.ndim` of both arrays.

In [23]:
# Write your code here
customer = np.array([175, 70, 28])

customers = np.array([[175, 70, 28],[162, 58, 24],[180, 82, 35],[168, 65, 30]])
print("Single customer:")
print(customer.shape)
print(customer.ndim)

print("\nFour customers:")
print(customers.shape)
print(customers.ndim)



Single customer:
(3,)
1

Four customers:
(4, 3)
2


### Q15. Indexing and slicing to build X and y
Create a 2-D array with 6 rows and 3 columns, where the last column is a target label (0 or 1) and the first two columns are features (make up your own numbers).
1. Print the first 3 rows only.
2. Print only the first column, for all rows.
3. Split the array into `X` (all columns except the last) and `y` (only the last column), and print both.

In [24]:
# Write your code here
import numpy as np

data = np.array([[1.5, 2.3, 0],[2.1, 3.4, 1],[3.2, 1.8, 0],[4.5, 2.9, 1],[5.1, 4.2, 1],[6.3, 3.7, 0]])

print(data[:3])
print(data[:, 0])

X = data[:, :-1]
y = data[:, -1]

print(X)
print(y)




[[1.5 2.3 0. ]
 [2.1 3.4 1. ]
 [3.2 1.8 0. ]]
[1.5 2.1 3.2 4.5 5.1 6.3]
[[1.5 2.3]
 [2.1 3.4]
 [3.2 1.8]
 [4.5 2.9]
 [5.1 4.2]
 [6.3 3.7]]
[0. 1. 0. 1. 1. 0.]


### Q16. Vectorized operations and boolean masking
Create a 1-D NumPy array of 8 exam scores (0-100) of your choice. Without using any loop:
1. Add 5 bonus marks to every score and print the result.
2. Print a boolean array showing which scores are 50 or above.
3. Print only the scores that are 50 or above using boolean masking.

In [25]:
# Write your code here
import numpy as np

scores = np.array([45, 67, 82, 39, 55, 91, 48, 73])

bonus_scores = scores + 5
print(bonus_scores)

passed = bonus_scores >= 50
print(passed)

print(bonus_scores[passed])




[50 72 87 44 60 96 53 78]
[ True  True  True False  True  True  True  True]
[50 72 87 60 96 53 78]
